### ISSUE TITLE
exception on deleting term from synset

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/openthesaurus#63]
Delete a term at e.g. http://localhost:8080/synonyme/edit/11637 - the term will be deleted but it seems the logging fails.

```
failed to lazily initialize a collection, could not initialize proxy - no Session. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:584)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
        at org.hibernate.collection.internal.AbstractPersistentCollection.readElementExistence(AbstractPersistentCollection.java:313)
        at org.hibernate.collection.internal.PersistentSet.contains(PersistentSet.java:154)
        at com.vionto.vithesaurus.Term.compareTo(Term.groovy:162)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at java.util.Collections.sort(Collections.java:175)
        at com.vionto.vithesaurus.Synset.toDetailedString(Synset.groovy:249)
        at com.vionto.vithesaurus.LogInfo.<init>(LogInfo.groovy:90)
        at openthesaurus.SynsetController.update(SynsetController.groovy:732)
        ... 14 common frames omitted
```

**Comment by kstuart** [comment]
I've not been able to reproduce this locally, even after importing your latest database dump. I can delete terms on the example ID you've given with no exceptions being thrown.

Do you see the issue when running a development profile?

![screenshot from 2018-12-03 15-49-37](https://user-images.githubusercontent.com/465920/49384733-8efa2e80-f713-11e8-8fab-ccb2e27b4df4.png)

**Comment by danielnaber** [comment]
Yes, it also happens locally and with `grails run-app`. I use JDK 1.8.0_121, which one do you test with?

**Comment by kstuart** [comment]
Most of the work and testing was done on:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-linux64) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-linux64) (build 25.181-b02, mixed mode)
```

MariaDB:
`mysql  Ver 15.1 Distrib 10.3.10-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

I've just switched to:
```
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)
```

And am not seeing any issues.

If you want to try Zulu I installed using [SDKMAN](https://sdkman.io/),  you can also download from [Azul Systems](https://www.azul.com/downloads/zulu/zulu-linux/).

Also, when you say logging you mean the *change log* on the *synonym* page?

**Comment by danielnaber** [comment]
> Also, when you say logging you mean the change log on the synonym page?

Yes

**Comment by danielnaber** [comment]
@kstuart Maybe you cannot reproduce it because this line is commented out in your `application-*.properties`?

`thesaurus.topSortTag=haupts\u00e4chlich benutzte Form`

Without that line commented in, the code never gets executed.

**Comment by danielnaber** [comment]
I might have found a workaround (https://github.com/danielnaber/openthesaurus/commit/dc0e36b8c901c5d7cbebae6c7f7e0d9159065b55) - will deploy later and let it run for some time.
